@rem NB that you can call it like go --debug, except you can't since there's no gems in a jruby-complete jar...
call java -jar vendor\jruby-complete-1.6.2.jar %* bin\sensible-cinema  --online-player-mode --go
