# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sensible-cinema}
  s.version = "0.23.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roger Pack"]
  s.date = %q{2011-06-27}
  s.email = %q{rogerdpack@gmail.com}
  s.executables = ["sensible-cinema", "sensible-cinema-cli"]
  s.extra_rdoc_files = [
    "LICENSE.TXT",
    "README",
    "TODO"
  ]
  s.files = [
    "LICENSE.TXT",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "_DO_NOT_RUN_IT_FROM_HERE_DOWNLOAD_THE_RELEASE_ZIP_INSTEAD",
    "bin/sensible-cinema",
    "bin/sensible-cinema-cli",
    "business_ideas.txt",
    "change_log_with_feature_list.txt",
    "development.txt",
    "experimental_ocr_readme.txt",
    "go.bat",
    "go.sh",
    "go_ocr_tracker.bat",
    "goc.bat",
    "gplv3.txt",
    "how_to_create_your_own_delete_lists.txt",
    "is_it_legal_to_copy_dvds.txt",
    "legal/md5s.txt",
    "legal/transcript_mute_vlc.txt",
    "legal2",
    "lib/add_any_bundled_gems_to_load_path.rb",
    "lib/auto_convert.rb",
    "lib/blanker.rb",
    "lib/check_installed_mac.rb",
    "lib/count_down_timer_jruby_swing.rb",
    "lib/drive_info.rb",
    "lib/edl_converter.rb",
    "lib/edl_parser.rb",
    "lib/fake_blanker.rb",
    "lib/file_chooser.rb",
    "lib/frame_accurate.rb",
    "lib/keyboard_input.rb",
    "lib/mencoder_wrapper.rb",
    "lib/mouse.rb",
    "lib/mouse_forever.rb",
    "lib/mplayer_edl.rb",
    "lib/muter.rb",
    "lib/ocr.rb",
    "lib/overlayer.rb",
    "lib/play_audio.rb",
    "lib/screen_tracker.rb",
    "lib/storage.rb",
    "lib/subtitle_profanity_finder.rb",
    "lib/swing_helpers.rb",
    "lib/vlc_programmer.rb",
    "never_do",
    "ocr.todo_if_need_speed",
    "preamble",
    "sensible-cinema.gemspec",
    "spec/arse.srt",
    "spec/blanker.spec.rb",
    "spec/common.rb",
    "spec/convert_image.rb",
    "spec/deity_end.srt",
    "spec/dragon.srt",
    "spec/drive_info.spec.rb",
    "spec/edl_parser.spec.rb",
    "spec/frame_accurate.spec.rb",
    "spec/go_line.bat",
    "spec/how_to",
    "spec/keyboard_input.spec.rb",
    "spec/mencoder_wrapper.spec.rb",
    "spec/mouse.spec.rb",
    "spec/mplayer_edl.spec.rb",
    "spec/muter.spec.rb",
    "spec/notes",
    "spec/ocr.spec.rb",
    "spec/overlayer.spec.rb",
    "spec/screen_tracker.spec.rb",
    "spec/sensible_cinema_gui.spec.rb",
    "spec/subtitle_profanity_finder.spec.rb",
    "spec/swing_helpers.spec.rb",
    "spec/test_yaml.yml",
    "spec/vlc_programmer.spec.rb",
    "template_bats/RUN SENSIBLE CINEMA CLICK HERE.bat",
    "template_bats/advanced--create or edit sensible cinema delete list files.bat",
    "todo.build_library.txt",
    "todo.inventionzy.txt",
    "todo.open_edl_list_org.txt",
    "todo.propaganda",
    "todo.subtitle",
    "vendor/jruby-complete-1.6.2.jar",
    "vendor/mac_dvdid/bin/dvdid",
    "vendor/mac_dvdid/include/dvdid/dvdid.h",
    "vendor/mac_dvdid/include/dvdid/dvdid2.h",
    "vendor/mac_dvdid/include/dvdid/export.h",
    "vendor/mac_dvdid/lib/libdvdid.0.dylib",
    "vendor/mac_dvdid/lib/libdvdid.a",
    "vendor/mac_dvdid/lib/libdvdid.dylib",
    "vendor/mac_dvdid/lib/libdvdid.la",
    "vendor/monkey.png",
    "vendor/readme.txt",
    "www/index.html",
    "zamples/edit_decision_lists/category descriptions.txt",
    "zamples/edit_decision_lists/dvds/COOL_RUNNINGS.txt",
    "zamples/edit_decision_lists/dvds/Harry Potter 2.txt",
    "zamples/edit_decision_lists/dvds/bambi.txt",
    "zamples/edit_decision_lists/dvds/big_buck_bunny_dvd.txt",
    "zamples/edit_decision_lists/dvds/bob the builder pets in a pickle.txt",
    "zamples/edit_decision_lists/dvds/bobs_big_plan.txt",
    "zamples/edit_decision_lists/dvds/example_delete_list.txt",
    "zamples/edit_decision_lists/dvds/happiest baby on the block.txt",
    "zamples/edit_decision_lists/dvds/how_to_train_your_dragon.txt",
    "zamples/edit_decision_lists/dvds/kung_fu_panda_1.txt",
    "zamples/edit_decision_lists/dvds/legend_of_the_guardians_the_owls_of_gahoole.txt",
    "zamples/edit_decision_lists/dvds/making_marriage_work.txt",
    "zamples/edit_decision_lists/dvds/narnia_voyage_of_the_dawn_treader.txt",
    "zamples/edit_decision_lists/dvds/old_and_inaccurate/White Christmas.txt",
    "zamples/edit_decision_lists/dvds/old_and_inaccurate/all_dogs_go_to_heaven.txt",
    "zamples/edit_decision_lists/dvds/old_and_inaccurate/cars_disney.txt",
    "zamples/edit_decision_lists/dvds/old_and_inaccurate/happy_feet.txt",
    "zamples/edit_decision_lists/dvds/old_and_inaccurate/labyrinth.txt",
    "zamples/edit_decision_lists/dvds/old_and_inaccurate/making marriage work.txt",
    "zamples/edit_decision_lists/dvds/old_and_inaccurate/star_trek_generations_hulu.txt",
    "zamples/edit_decision_lists/dvds/pack_wedding_2007-03-03.txt",
    "zamples/edit_decision_lists/dvds/sintel_open_source_blender.txt",
    "zamples/edit_decision_lists/dvds/tron_legacy.txt",
    "zamples/edit_decision_lists/dvds/turn_around_alma_younger.txt",
    "zamples/edit_decision_lists/dvds/zz_example_delete_list_that_has_no_cuts_in_it.txt",
    "zamples/edit_decision_lists/netflix_instant/greatest_story_ever_told_netflix.txt",
    "zamples/edit_decision_lists/old_not_yet_updated/example_edit_decision_list.txt",
    "zamples/edit_decision_lists/old_not_yet_updated/youtube/gummy_bear_song_youtube.txt",
    "zamples/edit_decision_lists/youtube/demo_mutes.txt",
    "zamples/edit_decision_lists/youtube/nuki_song_youtube.txt",
    "zamples/players/how_to_create_more_players.txt",
    "zamples/players/hulu/total_length_over_an_hour.txt",
    "zamples/players/netflix/netflix_firefox_non_maximized.txt",
    "zamples/players/vlc/full_screened_total_length_over_an_hour.txt",
    "zamples/players/vlc/windowed_total_length_over_an_hour.txt",
    "zamples/players/vlc/windowed_total_length_under_an_hour.txt",
    "zamples/players/youtube/full_screened_1024x768.txt",
    "zamples/players/youtube/full_screened_1152x864.txt",
    "zamples/players/youtube/full_screened_1680x1050.txt",
    "zamples/players/youtube/normal_in_youtube.com.chrome.txt",
    "zamples/players/youtube/note_these_assume_less_than_10_minutes_length.txt"
  ]
  s.homepage = %q{http://github.com/rdp}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.1}
  s.summary = %q{an EDL scene-selector/bleeper that works with online players like hulu}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<os>, [">= 0.9.3"])
      s.add_runtime_dependency(%q<sane>, [">= 0.22.0"])
      s.add_runtime_dependency(%q<rdp-win32screenshot>, [">= 0.0.7.3"])
      s.add_runtime_dependency(%q<mini_magick>, [">= 3.1"])
      s.add_runtime_dependency(%q<whichr>, [">= 0.3.6"])
      s.add_runtime_dependency(%q<jruby-win32ole>, [">= 0"])
      s.add_runtime_dependency(%q<rdp-ruby-wmi>, [">= 0"])
      s.add_runtime_dependency(%q<plist>, [">= 0"])
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<hitimes>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["> 2"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<hitimes>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<os>, [">= 0.9.3"])
      s.add_dependency(%q<sane>, [">= 0.22.0"])
      s.add_dependency(%q<rdp-win32screenshot>, [">= 0.0.7.3"])
      s.add_dependency(%q<mini_magick>, [">= 3.1"])
      s.add_dependency(%q<whichr>, [">= 0.3.6"])
      s.add_dependency(%q<jruby-win32ole>, [">= 0"])
      s.add_dependency(%q<rdp-ruby-wmi>, [">= 0"])
      s.add_dependency(%q<plist>, [">= 0"])
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<hitimes>, [">= 0"])
      s.add_dependency(%q<rspec>, ["> 2"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<hitimes>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<os>, [">= 0.9.3"])
    s.add_dependency(%q<sane>, [">= 0.22.0"])
    s.add_dependency(%q<rdp-win32screenshot>, [">= 0.0.7.3"])
    s.add_dependency(%q<mini_magick>, [">= 3.1"])
    s.add_dependency(%q<whichr>, [">= 0.3.6"])
    s.add_dependency(%q<jruby-win32ole>, [">= 0"])
    s.add_dependency(%q<rdp-ruby-wmi>, [">= 0"])
    s.add_dependency(%q<plist>, [">= 0"])
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<hitimes>, [">= 0"])
    s.add_dependency(%q<rspec>, ["> 2"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<hitimes>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

