#!/usr/bin/env bash
echo "attempting to load server to https://localhost:3000"
if [[ ! -f db/local_cookie_secret ]]; then
  crystal eval 'require "random/secure"; puts Random::Secure.hex(64)' > db/local_cookie_secret
fi
if [[ ! -d sessions ]]; then
  mkdir sessions
fi
if [[ ! -d edit_descriptors ]]; then
  mkdir edit_descriptors
fi
if [[ ! -f _key.pem ]]; then
  echo "generating dev ssl keys"
  /usr/local/Cellar/openssl/1.0.2s/bin/openssl req -x509 -newkey rsa:4096 -keyout _key.pem -out cert.pem -days 365 -nodes
fi
echo "building"
crystal build ./kemal_server.cr -o bin.kemal_server || exit 1
echo "running"
./bin.kemal_server --ssl --ssl-key-file _key.pem --ssl-cert-file cert.pem -p 3000 || exit 1
