#!/usr/bin/env fish
kqwait (find . | grep -v session | grep -v edit_descriptors | grep -v public/movie_images)
kill (pidof crystal | cut -d " " -f 1)
sleep 0.1
kill (pidof crystal | cut -d " " -f 1)

