#!/bin/bash
# bash for now until I know how to check for root using fish
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as sudo" 
  exit 1
else
  echo "root successfully enabled...we'll need that in a sec..."
  echo "use soon like https://playitmyway.org"
fi

# no release since super slow on DO plus crashes out of RAM :|
CRYSTAL_PATH=/home/rdp/dev/crystal.sometimes.used.them/src:lib sudo -E -u rdp crystal build ./kemal_server.cr || exit 1 # prime the pump :)
while true; do
  ./_prod_ssl_go # wait for it to get killed by cron or web server rebuild+restart etc.
done
